### ISSUE TITLE
Feature Request: Streak Penalty - Shuffle

### ISSUE THREAD

**Issue by CaseyWagner** [SummersideMakerspace/Concentration#1]
When a player goes on a streak, shuffle the location of X cards once the streak number has been achieved, and additionally for each streak point thereafter.

**Comment by ghost** [comment]
Great idea!

**Comment by CaseyWagner** [comment]
Really makes a difference!
![nopenalty](https://cloud.githubusercontent.com/assets/342544/15100649/18e2fcbc-154e-11e6-8b3c-c5da32971c04.png)
![twopenalty](https://cloud.githubusercontent.com/assets/342544/15100650/1ba48830-154e-11e6-99e9-cd6e00500549.png)
